### ISSUE TITLE
General To-Do

### ISSUE THREAD

**Issue by AJSmyth** [AJSmyth/chess#1]
### Valid moves must
- not expose king to check
- not move through other pieces (excluding knight)
- follow the defined behavior of the piece

Move functions have the signature ```void getValidMovesPIECE(int f0, int r0, int f1, int r1, Board *b, MOVE **m)```, where
    - f0r0 is the source file and rank
    - f1r1 is the destination file and rank

## To-do
- [x] getValidMovesQueen:    @neelsankaran 
- [x] getValidMovesRook:    @AJSmyth
- [x] getValidMovesKnight:    @development365 
- [x] getValidMovesBishop:    @iankuys
- [x] getValidMovesKing:     @sandeepr03 
- [x] getValidMovesPawn:    @jmqueen01
- [x] getValidMoves: @neelsankaran 
- [x] Update function signatures of getValidMovePIECE: @neelsankaran 
    - old => void getValidMovePIECE(int f0, int r0, Board *b, Move ** m)
- [x] Castling: @sandeepr03
- [x] En Passant @jmqueen01 
- [x] Chess Algebraic Notation: @iankuys 
    - [x] General CAN get function from move and board
    - [x] Print CAN to file
    - [x] Get CAN from file and execute moves
- [x] capture @sandeepr03 
- [x] promote @jmqueen01 
- [x] SimulateMove: @neelsankaran 
    - [ ] IsMated
        - [x] IsInCheck
             - [ ] GameState logic
- [ ] Fix Memory Leaks: @AJSmyth or @neelsankaran
